## 01_IMPORTING_LIBRARIES

In [1]:
from pathlib import Path

import numpy as np
import pandas as pd

from IPython.display import display

## 02_PROJECT_PATHS

In [2]:
PROJECT_ROOT = Path(
    r"C:\Users\bongo\OneDrive\Desktop\GitHub\Movie Analysis Predictor"
)

DATA_DIR = PROJECT_ROOT / "Data"

TARGET_DIR = DATA_DIR / "Prediction_Targets"

TARGET_DIR.mkdir(
    parents=True,
    exist_ok=True
)

TARGET_DATA_PATH = (
    TARGET_DIR
    / "prediction_targets.csv"
)

print("Prediction target directory:")
print(TARGET_DIR)

Prediction target directory:
C:\Users\bongo\OneDrive\Desktop\GitHub\Movie Analysis Predictor\Data\Prediction_Targets

## 03_LOCKING_THE_PREDICTION_TARGET_LIST

In [5]:
prediction_targets = pd.DataFrame({

    "title": [

        # Released / backtesting cohort
        "Spider-Man: Brand New Day",
        "Michael",
        "The Odyssey",
        "Scary Movie",
        "Mortal Kombat II",
        "The Super Mario Galaxy Movie",
        "The Devil Wears Prada 2",
        "Toy Story 5",
        "GOAT",
        "Backrooms",
        "The Cat in the Hat",

        # Future prediction cohort
        "Dune: Part Three",
        "Avengers: Doomsday",
        "Shrek 5",
        "Jumanji: Open World",
        "Street Fighter",
        "The Batman Part II",
        "Spider-Man: Beyond the Spider-Verse",
        "Children of Blood and Bone"
    ],

    "cohort": [

        "released_backtest",
        "released_backtest",
        "released_backtest",
        "released_backtest",
        "released_backtest",
        "released_backtest",
        "released_backtest",
        "released_backtest",
        "released_backtest",
        "released_backtest",
        "released_backtest",

        "future_prediction",
        "future_prediction",
        "future_prediction",
        "future_prediction",
        "future_prediction",
        "future_prediction",
        "future_prediction",
        "future_prediction"
    ]
})


print("=" * 80)
print("PREDICTION TARGET REGISTER")
print("=" * 80)

print(
    f"Total target movies: "
    f"{len(prediction_targets)}"
)

print()

print(
    prediction_targets["cohort"]
    .value_counts()
)

display(prediction_targets)

================================================================================
PREDICTION TARGET REGISTER
================================================================================
Total target movies: 19

cohort
released_backtest    11
future_prediction     8
Name: count, dtype: int64

                                  title             cohort
0             Spider-Man: Brand New Day  released_backtest
1                               Michael  released_backtest
2                           The Odyssey  released_backtest
3                           Scary Movie  released_backtest
4                      Mortal Kombat II  released_backtest
5          The Super Mario Galaxy Movie  released_backtest
6               The Devil Wears Prada 2  released_backtest
7                           Toy Story 5  released_backtest
8                                  GOAT  released_backtest
9                             Backrooms  released_backtest
10                   The Cat in the Hat  released_backtest
11                     Dune: Part Three  future_prediction
12                   Avengers: Doomsday  future_prediction
13                              Shrek 5  future_prediction
14                  Jumanji: Open World  future_prediction
15                       Street Fighter  future_prediction
16                   The Batman Part II  future_prediction
17  Spider-Man: Beyond the Spider-Verse  future_prediction
18           Children of Blood and Bone  future_prediction

## 04 DEFINING THE DATA WE ACTUALLY NEED

In [6]:
target_features = [

    # Identity
    "title",
    "release_date",
    "release_year",

    # Core movie characteristics
    "budget",
    "genre",
    "studio",
    "production_company",

    # Talent
    "director",
    "lead_cast",

    # Franchise information
    "is_franchise",
    "is_sequel",
    "franchise_name",
    "franchise_gap_years",

    # Release strategy
    "release_month",
    "release_season",
    "holiday_release",

    # Pre-release signals
    "pre_release_sentiment",
    "social_interest",

    # Historical strength
    "director_track_record",
    "cast_track_record",

    # Collection metadata
    "data_as_of",
    "source_notes"
]


print("=" * 80)
print("TARGET DATA COLLECTION SCHEMA")
print("=" * 80)

for number, feature in enumerate(
    target_features,
    start=1
):
    print(
        f"{number:02}. {feature}"
    )

================================================================================
TARGET DATA COLLECTION SCHEMA
================================================================================
01. title
02. release_date
03. release_year
04. budget
05. genre
06. studio
07. production_company
08. director
09. lead_cast
10. is_franchise
11. is_sequel
12. franchise_name
13. franchise_gap_years
14. release_month
15. release_season
16. holiday_release
17. pre_release_sentiment
18. social_interest
19. director_track_record
20. cast_track_record
21. data_as_of
22. source_notes

## 05 VERFIED TARGET REGISTER

In [7]:
verified_targets = pd.DataFrame([

    # RELEASED / BACKTEST

    {
        "title": "Spider-Man: Brand New Day",
        "cohort": "released_backtest",
        "release_status": "released",
        "release_date": "2026-07-31",
        "studio_distributor": "Sony Pictures / Marvel Studios",
        "director": "Destin Daniel Cretton",
        "source_name": "Sony Pictures"
    },

    {
        "title": "Michael",
        "cohort": "released_backtest",
        "release_status": "released",
        "release_date": "2026-04-24",
        "studio_distributor": "Lionsgate",
        "director": "Antoine Fuqua",
        "source_name": "Lionsgate / Variety"
    },

    {
        "title": "The Odyssey",
        "cohort": "released_backtest",
        "release_status": "released",
        "release_date": "2026-07-17",
        "studio_distributor": "Universal Pictures",
        "director": "Christopher Nolan",
        "source_name": "Universal / Variety"
    },

    {
        "title": "Scary Movie",
        "cohort": "released_backtest",
        "release_status": "released",
        "release_date": "2026-06-05",
        "studio_distributor": "Paramount Pictures / Miramax",
        "director": "Michael Tiddes",
        "source_name": "Paramount"
    },

    {
        "title": "Mortal Kombat II",
        "cohort": "released_backtest",
        "release_status": "released",
        "release_date": "2026-05-08",
        "studio_distributor": "Warner Bros. Pictures / New Line Cinema",
        "director": "Simon McQuoid",
        "source_name": "Warner Bros."
    },

    {
        "title": "The Super Mario Galaxy Movie",
        "cohort": "released_backtest",
        "release_status": "released",
        "release_date": "2026-04-03",
        "studio_distributor": "Universal Pictures / Illumination / Nintendo",
        "director": "Aaron Horvath; Michael Jelenic; Pierre Leduc",
        "source_name": "Universal / Variety"
    },

    {
        "title": "The Devil Wears Prada 2",
        "cohort": "released_backtest",
        "release_status": "released",
        "release_date": "2026-05-01",
        "studio_distributor": "20th Century Studios",
        "director": "David Frankel",
        "source_name": "20th Century Studios"
    },

    {
        "title": "Toy Story 5",
        "cohort": "released_backtest",
        "release_status": "released",
        "release_date": "2026-06-19",
        "studio_distributor": "Disney / Pixar",
        "director": "Andrew Stanton",
        "source_name": "Pixar / Disney"
    },

    {
        "title": "GOAT",
        "cohort": "released_backtest",
        "release_status": "released",
        "release_date": "2026-02-13",
        "studio_distributor": "Columbia Pictures / Sony Pictures Animation",
        "director": "Tyree Dillihay",
        "source_name": "Sony Pictures"
    },

    {
        "title": "Backrooms",
        "cohort": "released_backtest",
        "release_status": "released",
        "release_date": "2026-05-29",
        "studio_distributor": "A24",
        "director": "Kane Parsons",
        "source_name": "A24"
    },

    {
        "title": "The Cat in the Hat",
        "cohort": "released_backtest",
        "release_status": "released",
        "release_date": "2026-02-26",
        "studio_distributor": "Warner Bros. Pictures Animation",
        "director": "Alessandro Carloni; Erica Rivinoja",
        "source_name": "Warner Bros. / Variety"
    },

    # FUTURE PREDICTIONS

    {
        "title": "Dune: Part Three",
        "cohort": "future_prediction",
        "release_status": "upcoming",
        "release_date": "2026-12-18",
        "studio_distributor": "Warner Bros. Pictures / Legendary",
        "director": "Denis Villeneuve",
        "source_name": "Warner Bros. / Variety"
    },

    {
        "title": "Avengers: Doomsday",
        "cohort": "future_prediction",
        "release_status": "upcoming",
        "release_date": "2026-12-18",
        "studio_distributor": "Marvel Studios / Disney",
        "director": "Anthony Russo; Joe Russo",
        "source_name": "Disney"
    },

    {
        "title": "Shrek 5",
        "cohort": "future_prediction",
        "release_status": "upcoming",
        "release_date": "2027-06-30",
        "studio_distributor": "DreamWorks Animation / Universal Pictures",
        "director": "Conrad Vernon; Walt Dohrn",
        "source_name": "DreamWorks / Variety"
    },

    {
        "title": "Jumanji: Open World",
        "cohort": "future_prediction",
        "release_status": "upcoming",
        "release_date": "2026-12-25",
        "studio_distributor": "Sony Pictures / Columbia Pictures",
        "director": "Jake Kasdan",
        "source_name": "Sony / Variety"
    },

    {
        "title": "Street Fighter",
        "cohort": "future_prediction",
        "release_status": "upcoming",
        "release_date": "2026-10-16",
        "studio_distributor": "Paramount Pictures / Legendary / Capcom",
        "director": "Kitao Sakurai",
        "source_name": "Paramount / Variety"
    },

    {
        "title": "The Batman Part II",
        "cohort": "future_prediction",
        "release_status": "upcoming",
        "release_date": "2028-02-18",
        "studio_distributor": "Warner Bros. Pictures / DC Studios",
        "director": "Matt Reeves",
        "source_name": "Warner Bros. / Variety"
    },

    {
        "title": "Spider-Man: Beyond the Spider-Verse",
        "cohort": "future_prediction",
        "release_status": "upcoming",
        "release_date": "2027-06-18",
        "studio_distributor": "Sony Pictures Animation",
        "director": "Bob Persichetti; Justin K. Thompson",
        "source_name": "Sony / Variety"
    },

    {
        "title": "Children of Blood and Bone",
        "cohort": "future_prediction",
        "release_status": "upcoming",
        "release_date": "2027-01-15",
        "studio_distributor": "Paramount Pictures",
        "director": "Gina Prince-Bythewood",
        "source_name": "Paramount"
    }
])


verified_targets["release_date"] = pd.to_datetime(
    verified_targets["release_date"]
)

verified_targets["release_year"] = (
    verified_targets["release_date"].dt.year
)


display(verified_targets)

,title,cohort,release_status,release_date,studio_distributor,director,source_name,release_year
0,Spider-Man: Brand New Day,released_backtest,released,2026-07-31,Sony Pictures / Marvel Studios,Destin Daniel Cretton,Sony Pictures,2026
1,Michael,released_backtest,released,2026-04-24,Lionsgate,Antoine Fuqua,Lionsgate / Variety,2026
2,The Odyssey,released_backtest,released,2026-07-17,Universal Pictures,Christopher Nolan,Universal / Variety,2026
3,Scary Movie,released_backtest,released,2026-06-05,Paramount Pictures / Miramax,Michael Tiddes,Paramount,2026
4,Mortal Kombat II,released_backtest,released,2026-05-08,Warner Bros. Pictures / New Line Cinema,Simon McQuoid,Warner Bros.,2026
5,The Super Mario Galaxy Movie,released_backtest,released,2026-04-03,Universal Pictures / Illumination / Nintendo,Aaron Horvath; Michael Jelenic; Pierre Leduc,Universal / Variety,2026
6,The Devil Wears Prada 2,released_backtest,released,2026-05-01,20th Century Studios,David Frankel,20th Century Studios,2026
7,Toy Story 5,released_backtest,released,2026-06-19,Disney / Pixar,Andrew Stanton,Pixar / Disney,2026
8,GOAT,released_backtest,released,2026-02-13,Columbia Pictures / Sony Pictures Animation,Tyree Dillihay,Sony Pictures,2026
9,Backrooms,released_backtest,released,2026-05-29,A24,Kane Parsons,A24,2026
10,The Cat in the Hat,released_backtest,released,2026-02-26,Warner Bros. Pictures Animation,Alessandro Carloni; Erica Rivinoja,Warner Bros. / Variety,2026
11,Dune: Part Three,future_prediction,upcoming,2026-12-18,Warner Bros. Pictures / Legendary,Denis Villeneuve,Warner Bros. / Variety,2026
12,Avengers: Doomsday,future_prediction,upcoming,2026-12-18,Marvel Studios / Disney,Anthony Russo; Joe Russo,Disney,2026
13,Shrek 5,future_prediction,upcoming,2027-06-30,DreamWorks Animation / Universal Pictures,Conrad Vernon; Walt Dohrn,DreamWorks / Variety,2027
14,Jumanji: Open World,future_prediction,upcoming,2026-12-25,Sony Pictures / Columbia Pictures,Jake Kasdan,Sony / Variety,2026
15,Street Fighter,future_prediction,upcoming,2026-10-16,Paramount Pictures / Legendary / Capcom,Kitao Sakurai,Paramount / Variety,2026
16,The Batman Part II,future_prediction,upcoming,2028-02-18,Warner Bros. Pictures / DC Studios,Matt Reeves,Warner Bros. / Variety,2028
17,Spider-Man: Beyond the Spider-Verse,future_prediction,upcoming,2027-06-18,Sony Pictures Animation,Bob Persichetti; Justin K. Thompson,Sony / Variety,2027
18,Children of Blood and Bone,future_prediction,upcoming,2027-01-15,Paramount Pictures,Gina Prince-Bythewood,Paramount,2027

## 06 ADD PREDICTION FEATURE COLLECTION COLUMNS

In [8]:
target_data = verified_targets.copy()


new_columns = {

    # Core characteristics
    "budget": np.nan,
    "budget_type": pd.NA,

    "genre": pd.NA,

    "production_company": pd.NA,

    "lead_cast": pd.NA,

    # Franchise
    "is_franchise": pd.NA,
    "is_sequel": pd.NA,
    "franchise_name": pd.NA,
    "franchise_gap_years": np.nan,

    # Release timing
    "release_month": np.nan,
    "release_season": pd.NA,
    "holiday_release": pd.NA,

    # Pre-release signals
    "pre_release_sentiment": np.nan,
    "social_interest": np.nan,

    # Historical performance
    "director_track_record": np.nan,
    "cast_track_record": np.nan,

    # Released cohort outcome
    "worldwide_box_office": np.nan,

    # Data quality
    "data_as_of": "2026-09-08",
    "collection_notes": pd.NA
}


for column, default_value in new_columns.items():

    target_data[column] = default_value


display(target_data.head())

,title,cohort,release_status,release_date,studio_distributor,director,source_name,release_year,budget,budget_type,...,release_month,release_season,holiday_release,pre_release_sentiment,social_interest,director_track_record,cast_track_record,worldwide_box_office,data_as_of,collection_notes
0,Spider-Man: Brand New Day,released_backtest,released,2026-07-31,Sony Pictures / Marvel Studios,Destin Daniel Cretton,Sony Pictures,2026,NaN,<NA>,...,NaN,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,2026-09-08,<NA>
1,Michael,released_backtest,released,2026-04-24,Lionsgate,Antoine Fuqua,Lionsgate / Variety,2026,NaN,<NA>,...,NaN,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,2026-09-08,<NA>
2,The Odyssey,released_backtest,released,2026-07-17,Universal Pictures,Christopher Nolan,Universal / Variety,2026,NaN,<NA>,...,NaN,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,2026-09-08,<NA>
3,Scary Movie,released_backtest,released,2026-06-05,Paramount Pictures / Miramax,Michael Tiddes,Paramount,2026,NaN,<NA>,...,NaN,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,2026-09-08,<NA>
4,Mortal Kombat II,released_backtest,released,2026-05-08,Warner Bros. Pictures / New Line Cinema,Simon McQuoid,Warner Bros.,2026,NaN,<NA>,...,NaN,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,2026-09-08,<NA>

## 07 DERIVING RELEASE TIME

In [9]:
target_data["release_month"] = (
    target_data["release_date"]
    .dt.month
)


def assign_release_season(month):

    if month in [12, 1, 2]:
        return "summer_southern"

    elif month in [3, 4, 5]:
        return "autumn_southern"

    elif month in [6, 7, 8]:
        return "winter_southern"

    elif month in [9, 10, 11]:
        return "spring_southern"

    return pd.NA


target_data["release_season"] = (
    target_data["release_month"]
    .apply(assign_release_season)
)


display(
    target_data[
        [
            "title",
            "release_date",
            "release_year",
            "release_month",
            "release_season"
        ]
    ]
)

,title,release_date,release_year,release_month,release_season
0,Spider-Man: Brand New Day,2026-07-31,2026,7,winter_southern
1,Michael,2026-04-24,2026,4,autumn_southern
2,The Odyssey,2026-07-17,2026,7,winter_southern
3,Scary Movie,2026-06-05,2026,6,winter_southern
4,Mortal Kombat II,2026-05-08,2026,5,autumn_southern
5,The Super Mario Galaxy Movie,2026-04-03,2026,4,autumn_southern
6,The Devil Wears Prada 2,2026-05-01,2026,5,autumn_southern
7,Toy Story 5,2026-06-19,2026,6,winter_southern
8,GOAT,2026-02-13,2026,2,summer_southern
9,Backrooms,2026-05-29,2026,5,autumn_southern
10,The Cat in the Hat,2026-02-26,2026,2,summer_southern
11,Dune: Part Three,2026-12-18,2026,12,summer_southern
12,Avengers: Doomsday,2026-12-18,2026,12,summer_southern
13,Shrek 5,2027-06-30,2027,6,winter_southern
14,Jumanji: Open World,2026-12-25,2026,12,summer_southern
15,Street Fighter,2026-10-16,2026,10,spring_southern
16,The Batman Part II,2028-02-18,2028,2,summer_southern
17,Spider-Man: Beyond the Spider-Verse,2027-06-18,2027,6,winter_southern
18,Children of Blood and Bone,2027-01-15,2027,1,summer_southern

## 08 VALIDATE PREDICTION REGISTER

In [10]:
print("=" * 80)
print("PREDICTION TARGET VALIDATION")
print("=" * 80)


print(
    f"Total targets: "
    f"{len(target_data)}"
)

print(
    f"Unique titles: "
    f"{target_data['title'].nunique()}"
)

print(
    f"Missing release dates: "
    f"{target_data['release_date'].isna().sum()}"
)

print(
    f"Missing directors: "
    f"{target_data['director'].isna().sum()}"
)


print("\nCOHORTS")
print("-" * 40)

print(
    target_data[
        "cohort"
    ].value_counts()
)


print("\nRELEASE STATUS")
print("-" * 40)

print(
    target_data[
        "release_status"
    ].value_counts()
)

================================================================================
PREDICTION TARGET VALIDATION
================================================================================
Total targets: 19
Unique titles: 19
Missing release dates: 0
Missing directors: 0

COHORTS
----------------------------------------
cohort
released_backtest    11
future_prediction     8
Name: count, dtype: int64

RELEASE STATUS
----------------------------------------
release_status
released    11
upcoming     8
Name: count, dtype: int64

## 09 SAVE INITIAL TARGET REGISTER

In [11]:
TARGET_DATA_PATH = (
    TARGET_DIR
    / "prediction_targets.csv"
)


target_data.to_csv(
    TARGET_DATA_PATH,
    index=False
)


print("=" * 80)
print("PREDICTION TARGET DATA SAVED")
print("=" * 80)

print(TARGET_DATA_PATH)

================================================================================
PREDICTION TARGET DATA SAVED
================================================================================
C:\Users\bongo\OneDrive\Desktop\GitHub\Movie Analysis Predictor\Data\Prediction_Targets\prediction_targets.csv